//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace TeduShop.Model
{
 
    public partial class FooterModel
    {
        [Key]
        [MaxLength(50)]
        public byte[] ID { set; get; }

        [Required]
        public string Content { set; get; }
    }
}
