//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeduShop.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PostTagModel
    {
        [Key]
        public int ID { get; set; }
        [Key]
        public int PostID { get; set; }
        [Key]
        [MaxLength(50)]
        public string TagID { get; set; }
    
    }
}
